# Generated from MudOS save via scripts/mudos_save_translator.py
# Do not edit manually.

SOUL = {
    "messages": {},
    "def_messages": {},
    "emotes": {
        "grind": {"LIV": "$N $vgrind $r against $t.", "": "$N $vbump and $vgrind."},
        "document": {"STR": "%^CYAN%^# $o -$n"},
        "smooch": {
            "LIV": "$N $vplant a giant smooch right on $p1 mouth.",
            "STR": "$N $vsmooch $o.",
            "": "$N $vpractice kissing on $p arm.",
        },
        "tildar": {"": "tl;dr (too long; didn't read) -$N"},
        "glance": {
            "LIV": "$N $vglance at $t.",
            "STR": "$N $vglance $o.",
            "": "$N $vglance around.",
        },
        "deny": {"": "$N vigorously $vdeny it."},
        "wedgie": {
            "LIV": "$N $vgive $t an atomic wedgie.",
            "": "$N $vattempt to give $r a wedgie.",
        },
        "babble": {
            "LIV": "$N $vbabble incoherently at $t.",
            "": "$N $vbabble like an idiot.",
        },
        "nc": {"": '$N $vsigh, "No comment."'},
        "tv": {
            "STR": '%^BOLD%^%^BLUE%^$N $vquote a television show%^RESET%^, "$o"',
            "": "$N cannot remember a quote from that one television show.",
        },
        "jab": {"LIV": "$N $vthink $t $v1are just another bitch."},
        "wait": {
            "LIV": "$N $vwait for $t.",
            "STR": "$N $vwait $o.",
            "": "$N $vwait patiently.",
        },
        "gosh": {"": '$N $vexclaim, "Gosh!"'},
        "necria": {
            "LIV": "$N $vthink $t $v1are disturbing.",
            "STR": "$N $vthink $o is disturbing.",
            "": "$N $vthink something is disturbing.",
        },
        "eek": {
            "LIV": '$N $vpoint at $t and $vexclaim, "Eek!"',
            "STR": '$N $vexclaim, "Eek!! $o!"',
            "": '$N $vexclaim, "Eek!!"',
        },
        "sick": {"": "$N $vlook sick."},
        "chant": {
            "STR": '%^BOLD%^%^BLUE%^$N $vchant%^RESET%^, "$o ... $o ... $o ... $o ..."'
        },
        "strip": {"": "$N $vremove $p clothes seductively."},
        "jslowclap": {"LIV": "$N $vjoin $p1 slowclap.", "": "$N $vjoin the slowclap."},
        "pout": {
            "LIV": "$N $vmake puppy-dog eyes and $vpout at $t.",
            "STR": "$N $vpout $o.",
            "": "$N $vpout.",
        },
        "dill": {"": "The Dill has no soul."},
        "sdance": {
            "LIV": "$N $vput $p arms around $p1 waist and $vshare a slow dance with $t."
        },
        "me2": {"": '$N $vsay, "ME TOO"'},
        "flip": {
            "WRD": "$N $vflip $o.",
            "LIV": "$N $vflip $t high up in the air. Whee!",
            "": "$N $vflip.",
        },
        "overhead": {
            "LIV": "$N $vwatch $p joke sail over $p1 head.",
            "": "$N $vwatch $p joke sail over the head of $p audience.",
        },
        "show": {"LIV OBJ": "$N $vshow $t $p $o."},
        "hullah": {"": "$N $vare boring."},
        "blink": {
            "LIV": "$N $vblink at $t.",
            "LIV STR": "$N $vblink at $t $o.",
            "STR": "$N $vblink $o.",
            "": "$N $vblink.",
        },
        "movievoice": {
            "STR": '%^BLUE%^BOLD%^$N $vboom in the movie guy voice%^RESET%^, "$o"'
        },
        "belch": {
            "LIV": "$N $vbelch in $p1 face!",
            "STR": "$N $vbelch $o.",
            "": "$N $vbelch.",
        },
        "bah": {"LIV": '$N $vglare at $t and $vmutter, "Bah!"', "": '$N $vgo, "Bah!"'},
        "hand": {
            "LIV": [
                "$N $vkiss $p1 hand.",
                "$N $vkiss $p1 hand (how sweet).",
                "$N $vkiss your hand (how sweet).",
            ]
        },
        "stupid": {"": '$N $vhit $r on the head, cursing, "Stupid! Stupid! Stupid!"'},
        "bawl": {
            "LIV": "$N $vbawl $p eyes out on $p1 shoulder.",
            "STR": "$N $vbawl $o.",
            "": "$N $vbawl.",
        },
        "decrement": {"LIV": "$T --; # (decremented by $N)", "": "$N --"},
        "shriek": {
            "LIV": '$N $vshriek "Eeeeeeeeekk!" excitedly at $t.',
            "STR": "$N $vshriek $o.",
            "": "$N $vshriek.",
        },
        "gloat": {"STR": "$N $vgloat $o.", "": "$N $vgloat."},
        "backrub": {
            "LIV": "$N $vgive $t a backrub.",
            "": "$N $vwish somebody would give $no a backrub.",
        },
        "snowball": {"LIV": "$N $vpelt $t with a snowball! *SPLAT*"},
        "airguitar": {
            "LIV": "$N $vstrum wildly on an imaginary guitar, hoping $t will join in.",
            "": "$N $vstrum wildly on an imaginary guitar.",
        },
        "handshake": {"LIV": "$N $vshake $p1 hand."},
        "rap": {
            "STR": '%^BOLD%^%^BLUE%^$N $vrap%^RESET%^, "$o."',
            "": "$N $vrap like a dope whack niggy.",
        },
        "spank": {
            "LIV": "$N $vgive $t a good spanking!",
            "": "$N $vneed a good spanking.",
        },
        "doublebubble": {
            "LIV": "$N $vpour a double bubble for $t.",
            "": "$N $vpour $r a double bubble.",
        },
        "fail": {"": "$N $vsense a Fail in the Force."},
        "phew": {"": '$N $vgo, "PHEW!!"'},
        "dorn": {
            "LIV": '%^CYAN%^$N $vask $t%^RESET%^, "Is that proton club mix volume VIII? Well turn it UP MAN!"',
            "": "$N $vget really retarded about one subject and $vlose the ability to let it go.",
        },
        "piss": {
            "WRD LIV": "$N $vpiss $o on $t.",
            "LIV": "$N $vpiss on $t.",
            "STR": "$N $vpiss $o.",
            "": "$N $vpiss.",
        },
        "nibble": {
            "LIV": "$N $vnibble $p1 earlobe.",
            "LIV STR": "$N $vnibble $p1 earlobe $o.",
            "": "$N $vnibble the air around $nr. How odd!",
        },
        "pity": {
            "LIV": "$N $vthrow $t a pity party. 'Awwwwwwwww...'",
            "OBJ": "$N $vtake extreme pity on the $o.",
        },
        "meperiod": {"STR": "$N. $o.", "": "$N."},
        "slowclap": {
            "LIV": "$N $vstart the slow clap for $t.",
            "": "$N $vstart the slow clap.",
        },
        "shudder": {
            "LIV": "$N $vshudder in revulsion at $t.",
            "STR": "$N $vshudder $o.",
            "": "$N $vshudder.",
        },
        "ouch": {"": "$N $vexclaim, 'Ouch!'"},
        "nichus": {"": "$N $vget $p panties in a knot and $vlog out."},
        "squeal": {
            "LIV": '$N $vsqueal, "$t!! Hi!! How are you?!"',
            "LIV STR": '$N $vsqueal, "$t!! $o"',
            "STR": "$N $vsqueal $o.",
            "": "$N $vsqueal.",
        },
        "stretch": {
            "STR": "$N $vstretch $o.",
            "": '$N $varch $p back, $vstretch, then $vmutter "what next ..." under $p breath.',
        },
        "wink": {"LIV": "$N $vwink at $t.", "STR": "$N $vwink $o.", "": "$N $vwink."},
        "shoelace": {
            "LIV": "$N $vtie $p1 shoelaces together.",
            "LIV LIV": "$N $vtie $p1 shoelaces to $p2 shoes.",
        },
        "smil3": {"": "$N $vsmile really leet."},
        "admire": {"LIV": "$N $vadmire $t.", "OBJ": "$N $vadmire the $o."},
        "morons": {"": '$N $vshout, "I\'M SURROUNDED BY MORONS!"'},
        "tease": {"LIV": "$N $vtease $t.", "": "$N $vare -=SUCH=- a tease."},
        "dick": {"LIV": "$N $vthink $t $v1are being a [[dick++cunt]]."},
        "self": {"STR": "$N <------ $o."},
        "faith": {
            "LIV": "$N $vfind $p1 lack of faith disturbing.",
            "": '$N $vsay, "I find your lack of faith disturbing."',
        },
        "oops": {"": '$N $vgo, "Oops!"'},
        "dance": {
            "LIV": "$N $vdance the waltz with $t.",
            "STR": "$N $vdance $o.",
            "": "$N $vdance.",
        },
        "tongue": {
            "LIV": "$N $vstick out $p tongue at $t.",
            "": "$N $vstick out $p tongue.",
        },
        "mib": {"LIV": "$N $vmib at $t.", "": "$N $vmib."},
        "woah": {"": '$N $vgo, "Woah!"'},
        "bait": {"": "$N $vwait with baited breath."},
        "frobnicate": {
            "LIV": 'findPlayer("$T")->frobnicatedBy("$N")',
            "STR": 'findPlayer("$N")->frobnicateUsing("$o")',
            "": 'findPlayer("$N")->frobnicate()',
        },
        "sniffle": {
            "LIV": "$N $vsniffle at $t.",
            "STR": "$N $vsniffle $o.",
            "": "$N $vsniffle.",
            "at LIV": "$N $vsniffle at $t.",
        },
        "pfunk": {
            "LIV": '%^CYAN%^$N $vbreak $p mouse and $vblame $t%^RESET%^, "This game is a MESS!"',
            "": "$N literally cannot operate channels.",
        },
        "details": {
            "": "$N $vinterject every little mundane detail about $p stupid long boring day."
        },
        "outass": {"LIV": "$N can *SO* outass $t."},
        "frolick": {
            "LIV": "$N $vfrolick about with $t.",
            "STR": "$N $vfrolick $o.",
            "": "$N $vfrolick about.",
        },
        "cheer": {
            "LIV": "$N $vcheer for $t.",
            "STR": "$N $vcheer $o.",
            "": "$N $vlet out a resounding cheer!",
        },
        "slap": {
            "LIV": "$N $vslap $t across the face.",
            "": '$N $vslap $p forehead and $vgo, "D\'oh!"',
        },
        "bbl": {"": '$N $vgrumble and $vmutter "Be Back Later".'},
        "ponder": {
            "LIV": "$N $vwonder what $t $v1are saying.",
            "STR": "$N $vponder $o.",
            "": "$N $vponder the situation.",
        },
        "storm": {
            "LIV": "$N $vstorm about, gesturing wildly, and throwing things at $t.",
            "STR": "$N $vstorm around angrily cursing and gesturing wildly about $o.",
        },
        "ohohoh": {
            "": '$N $vraise $p hand, $vjump up and down, and excitedly $vscream, "Oh! Oh! Oh!"'
        },
        "smiel": {
            "LIV": "$N $vsmiel at $t.",
            "STR at LIV": "$N $vsmiel $o at $t.",
            "STR LIV": "$N $vsmiel $o at $t.",
            "at LIV STR": "=LIV STR",
            "LIV STR": "$N $vsmiel at $t $o.",
            "STR": "$N $vsmiel $o.",
            "": "$N $vsmiel.",
            "at LIV": "=LIV",
        },
        "flutter": {
            "LIV": "$N $vflutter $p eyelashes at $T.",
            "": "$N $vflutter $p eyelashes.",
        },
        "choke": {"LIV": "$N $vchoke $t!", "": "$N $vlaugh so hard $n $vchoke."},
        "quotewrong": {
            "STR": '%^BOLD%^%^BLUE%^$N $vremember something like%^RESET%^, "$o."'
        },
        "tengu": {"": "$N $vremembered that wrong."},
        "grimace": {
            "LIV": "$N $vgrimace at the very thought of life with $t.",
            "STR": "$N $vgrimace $o.",
            "": "$N $vgrimace.",
        },
        "groan": {
            "LIV": "$N $vgroan at $t.",
            "STR": "$N $vgroan $o.",
            "": "$N $vgroan.",
        },
        "wonder": {
            "LIV": "$N $vwonder about $p1 sanity.",
            "LIV STR": "$N $vwonder about $p1 $o.",
            "STR": "$N $vwonder $o.",
            "": "$N $vwonder.",
        },
        "taunt": {
            "LIV": "$N $vtaunt $t.",
            "LIV STR": '$N $vtaunt $t, "$o! $o! $o!" then $vgiggle hysterically.',
        },
        "typo": {"": "$N $vstroke $p lucky typing stick."},
        "craving": {
            "LIV": "$N $vlock $p eyes on $p1 crotch and $vdrool.",
            "": "$N $vhave a craving.",
        },
        "hop": {"STR": "$N $vhop $o.", "": "$N $vhop."},
        "wince": {
            "LIV": "$N $vwince away from $t.",
            "STR": "$N $vwince $o.",
            "": "$N $vwince.",
        },
        "cuddle": {"LIV": "$N $vcuddle with $t.", "": "$N $vare so cute and cuddly!"},
        "jk": {"LIV": '$N $vtell $t, "Just kidding!"', "": '$N $vsay, "Just kidding!"'},
        "shove": {
            "LIV": "$N $vshove $t.",
            "STR": "$N $vshove $o.",
            "": "$N $vshove $p invisible friend, Sally.",
        },
        "erd": {"": "$N $vthink that is effin roffle dude."},
        "eh": {"": '%^CYAN%^$N $vlook suprised and $vask%^RESET%^, "eh?"'},
        "breath": {"": "$N $vhold $p breath ..."},
        "headbutt": {"LIV": "$N $vheadbutt $t."},
        "glint": {"": "$N $vlook around with an evil glint in $p eye."},
        "bark": {
            "LIV": "$N $vbark like a dog at $t.",
            "STR": "$N $vbark $o.",
            "": "$N $vbark.",
        },
        "condescend": {
            "LIV": "$N $vhand $t a ball. Perhaps $n1 would like to bounce it?",
            "": "$N $vtalk down to everyone in the room.",
        },
        "fart": {
            "LIV": "$N $vpin $t down and $vfart on $t!",
            "": "$N $vlet out a stinky fart.",
        },
        "mosai": {
            "LIV": "$N $vjump around like the Mosai and even $vgive $t a hair-flick.",
            "": "$N $vstart jumping around like the Masai.",
        },
        "clear": {"": "$N $vclear $p throat... *ahem*"},
        "impatient": {"": "$N $vare getting impatient!"},
        "neurotic": {
            "": "$N $vpoint out $n $vare only neurotic, so there is nothing to worry about."
        },
        "soapbox": {
            "STR": '%^BOLD%^%^BLUE%^$N $vstep on the soapbox and $vstate%^RESET%^, "$o."'
        },
        "curses": {"": "$N $vcurse."},
        "tap": {
            "LIV": "$N $vtap $t on the shoulder.",
            "STR": "$N $vtap $p foot $o.",
            "": "$N $vtap $p foot.",
        },
        "pretzels": {
            "LIV": '%^BOLD%^BLUE%^$N $vattempt to one-up $t by loudly exclaiming%^RESET%^, "These pretzels are making me thirsty!"',
            "": '%^BOLD%^BLUE%^$N loudly $vexclaim%^RESET%^, "These pretzels are making me thirsty!"',
        },
        "raise": {"": "$N $vraise $p hand."},
        "noice": {
            "LIV": '$N $vshake $t and pointlessly $vinterject, "NOICE!"',
            "": '$N pointlessly $vinterject, "NOICE!"',
        },
        "quake": {"STR": "$N $vquake $o.", "": "$N $vquake."},
        "massacre": {"LIV": "$N $vmassacre $t into a small, bloody pile."},
        "salute": {
            "LIV": '$N $vsalute $t, "Aye Aye, Keptin!"',
            "STR": "$N $vsalute $o.",
            "": "$N $vsalute.",
        },
        "molest": {"LIV": "$N $vmolest $t."},
        "giantairquotes": {
            "STR": "%^BOLD%^%^BLUE%^$N $vuse giant air quotes%^RESET%^, 66 $o 99"
        },
        "windex": {
            "LIV": '$N $vask $t, "Do you wash your pants in windex?"',
            "": "$N $vlook like $n $vwant to wash some windows.",
        },
        "eep": {"": "$N $veep!"},
        "snarl": {"LIV": "$N $vsnarl at $t.", "": "$N $vsnarl."},
        "stagger": {"STR": "$N $vstagger $o.", "": "$N $vstagger drunkenly."},
        "think": {"STR": "$N . o O ( $o )"},
        "faint": {
            "LIV": "$N $vfaint into $p1 arms.",
            "": [
                "-=THUD=- You wake up quite groggy, realizing you have just fainted.\n",
                "$N faints.\n",
            ],
        },
        "jokebomb": {
            "LIV": "$N $vtoss a jokebomb over $p1 shoulder.",
            "": "$N $vtoss a joke bomb.",
        },
        "forget": {
            "LIV": "$N $vforget about $t.",
            "LIV STR": "$N $vforget about $t $o.",
            "STR": "$N $vforget $o.",
            "": "$N $vforget.",
        },
        "smirl": {
            "LIV": "$N simultaneously $vsmirk and $vsmile at $t.",
            "STR": "$N simultaneously $vsmirk and $vsmile $o.",
            "": "$N simultaneously $vsmirk and $vsmile.",
        },
        "hint": {
            "LIV": '$N $vwink at $t and $vnudge $t knowningly saying, "Hint, Hint..."',
            "": "$N $vdrop a subtle hint.",
        },
        "fuckety": {"": '$N $vfrown and $vsay, "Fuckety fuck fuck fuck."'},
        "sscratch": {"": "$N $vscratch $r secretly."},
        "howl": {"STR": "$N $vhowl $o.", "": "$N $vhowl."},
        "fuck": {
            "LIV": "$N $vmount $t and $vstart humping like a mutherfucker.",
            "LIV STR": '$N $vcurse $t, "Fuck: $o, seriously."',
            "STR": '$N $vcurse, "Fuck: $o, seriously."',
            "": '$N $vfrown and $vsay, "Fuckety fuck fuck fuck."',
        },
        "okie": {
            "LIV": '$N $vhappily $vexclaim to $t, "Okie dokie!"',
            "": '$N happily $vexclaim, "Okie dokie!"',
        },
        "babelnudge": {"LIV": "$N $vnudge $t with knowledge."},
        "make": {
            "STR": "$N $vdo a make $o on something.",
            "": "$N $vattempt to make a package.",
        },
        "gack": {"": "$N $vgack."},
        "flirt": {"LIV": "$N $vflirt with $t.", "STR LIV": "$N $vflirt $o $t."},
        "snort": {
            "LIV": "$N $vsnort at $t.",
            "STR": "$N $vsnort $o.",
            "": "$N $vsnort.",
        },
        "radio": {
            "LIV": "$N $vsmoke $t down with $p radio weed.",
            "": "$N $vsmoke some radio weed.",
        },
        "erp": {
            "WRD": "$N $vyak $o.",
            "LIV": "$N $vhave selected $t as $p erp duct target.",
            "on LIV": "$N $verp on $t.",
            "STR": "$N $verp $o.",
            "": "$N $vlook for an erp duct.",
        },
        "grin": {
            "LIV": "$N $vgrin at $t.",
            "STR LIV": "$N $vgrin $o at $t.",
            "LIV STR": "$N $vgrin $o at $t.",
            "STR": "$N $vgrin $o.",
            "": "$N $vgrin.",
            "at LIV": "$N $vgrin at $t.",
        },
        "fondle": {"LIV": "$N $vfondle $t.", "": "$N $vfondle $r."},
        "tuck": {"LIV": '$N $vtuck $t into bed and $vwave "Goodnight".'},
        "avoid": {
            "LIV": "$N $vseem to avoid $t like the plague.",
            "": "$N $vseem to avoid everyone.",
        },
        "wah": {
            "LIV": "$N $vcry at $t like a big baby 'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAH!!!!!'.",
            "": "$N $vcry like a big baby 'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAH!!!!!'.",
        },
        "handwave": {
            "LIV": "$N $vwave $p hands in front of $p1 eyes.",
            "": "$N $vwave $p hands in the air.",
        },
        "er": {"": '$N $vstumble, "er..."'},
        "loserl": {
            "": "$N $vmake an L with $p right hand and $vhold it up to $p forehead."
        },
        "snore": {
            "LIV": "$N $vsnore at $t.",
            "LIV STR": "$N $vsnore $o at $t.",
            "STR": "$N $vsnore $o.",
            "": "$N $vsnore.",
        },
        "tantrum": {"": "$N $vdrop to the floor and $vpound $p fists in a tantrum."},
        "lick": {
            "LIV": "$N $vlick $t on the cheek.",
            "STR": "$N $vlick $o.",
            "": "$N $vlick $p lips.",
        },
        "yay": {"STR": '$N $vyell, "Yay $o!"', "": '$N $vyell, "Yay!"'},
        "argh": {"": '$N $vscream, "Arrrggghhh!!"'},
        "gag": {"": "$N $vgag."},
        "laugh": {
            "LIV": "$N $vlaugh at $t.",
            "OBJ": "$N $vlaugh at $o.",
            "LIV STR": "$N $vlaugh at $t concerning: $o",
            "STR": "$N $vlaugh about: $o.",
            "": "$N $vlaugh.",
        },
        "snicker": {
            "LIV": "$N $vsnicker at $t.",
            "LIV STR": "$N $vsnicker at $t $o.",
            "STR": "$N $vsnicker $o.",
            "": "$N $vsnicker.",
        },
        "mglint": {"LIV": "$N $vlook at $t with a mischevious glint in $p eyes."},
        "whistle": {
            "LIV": "$N $vwhistle at $t.",
            "LIV STR": "$N $vwhistle $o at $t.",
            "STR": "$N $vwhistle $o.",
            "": "$N $vwhistle.",
        },
        "gawk": {"LIV": "$N $vgawk at $t.", "": "$N $vgawk in slack jawed amazement."},
        "poker": {
            "LIV": "$N $vlick $t in the front, then $vpoke $t in the rear.",
            "": "$N $vshuffle a deck of cards.",
        },
        "nuts": {"": "nickle-nut: $100, half-nut: $250, ball: $500"},
        "scream": {
            "LIV": "$N $vscream at $t.",
            "LIV STR": "$N $vscream at $t $o!",
            "STR": "$N $vscream $o!",
            "": "$N $vscream.",
        },
        "shush": {"LIV": '$N $vgo to $t, "Shhhh!!!!!"', "": '$N $vgo, "Shhhh!!!!!"'},
        "tosh": {"": '$N $vpoint skyward and $vdeclare, "Tosh! All of this is Tosh!"'},
        "bow": {
            "LIV": "$N $vbow to $t.",
            "STR LIV": "$N $vbow $o to $t.",
            "STR to LIV": "=STR LIV",
            "STR": "$N $vbow $o.",
            "": "$N $vbow.",
        },
        "sever": {
            "LIV": "$N calmly $vdraw $p katana and $vsever $p1 head from $p1 body. Nothing personal, you know."
        },
        "quiver": {
            "WRD LIV": "$N $vquiver $o all over $t.",
            "LIV": "$N $vquiver all over $t.",
            "STR": "$N $vquiver $o.",
            "": "$N $vquiver.",
        },
        "boink": {"LIV": "$N $vboink $t.", "STR": "$N $vboink $o.", "": "$N $vboink."},
        "weed": {
            "LIV": "$N $vpass a joint to $t.",
            "OBJ": '$N $vpoint at $o and $vsay, "You put your weed in there!"',
            "": '$N $vsay, "You put your weed in there."',
        },
        "grr": {"STR": "$N $vgrr $o.", "": "$N $vgrr."},
        "chuckle": {
            "LIV": "$N $vchuckle at $t.",
            "LIV STR": "$N $vchuckle at $t $o.",
            "STR": "$N $vchuckle about: $o",
            "": "$N $vchuckle.",
        },
        "yum": {"": '$N $vpat $p tummy, and $vgo, "Yum, Yum."'},
        "simle": {
            "LIV": "$N $vthink $t $v1are like a simile.",
            "": "$N $vare like a simile.",
        },
        "shaltz": {
            "STR": '%^BOLD%^%^BLUE%^$N $vquote Dr. Shaltz%^RESET%^, "$o"',
            "": "$N $vknow Latin, philosophy, history, Old English and linguistics rather well.",
        },
        "upnod": {
            "LIV": "$N $vsnap $p head back in an upnod at $t.",
            "": "$N $vsnap $p head back in an upnod.",
        },
        "orate": {"STR": '%^BOLD%^%^BLUE%^$N $vorate%^RESET%^, "$o"'},
        "increment": {"LIV": "$T ++; # (incremented by $N)", "": "$N ++"},
        "nerves": {
            "LIV": "$N $vnote that $t $v1are getting on $p nerves.",
            "STR": "$N $vnote that $o is getting on $p nerves...",
            "": "$N $vnote that something is getting on $p nerves...",
        },
        "smiole": {"": '$N $vkiss $p fingers sharply and $vexclaim, "That\'s smiole!"'},
        "ZZy": {"": "$N $vsave $p shit and $vsend it out."},
        "beam": {"LIV": "$N $vbeam at $t.", "STR": "$N $vbeam $o.", "": "$N $vbeam."},
        "teabag": {"LIV": "$N {{$vrest $p nuts,,$vrub $p cooter}} on $p1 head."},
        "apologize": {"": "$N $vstutter stupidly."},
        "admit": {
            "STR": "$N $vadmit that it was, in fact, $n who added the $o emote.",
            "": "$N $vadmit it!",
        },
        "frown": {
            "LIV": "$N $vfrown at $t.",
            "STR": "$N $vfrown $o.",
            "": "$N $vfrown.",
        },
        "assfuck": {
            "LIV with STR": "$N $vforce the lag monster to fuck $t (it's lover) up the ass with $o.",
            "STR with STR": "$N $vforce the lag monster to fuck $o (it's lover) up the ass with $o1.",
        },
        "screech": {"": "$N $vscreech."},
        "ruffle": {
            "LIV": "$N $vruffle $p1 hair.",
            "LIV STR": "$N $vruffle $t $o.",
            "STR": "$N $vruffle $p $o.",
            "": "$N $vruffle $p feathers.",
        },
        "tkiss": {"LIV": "$N $vkiss $t tenderly on the lips."},
        "shame": {"": "$N $vhang $p head in shame."},
        "ass": {
            "LIV": "$N $vrub $p smelly, hairy ass on $t.",
            "": "$N $vbehave like an ass.",
        },
        "chicken": {
            "LIV": "$N $vdo the chicken dance with $t.",
            "": "$N $vwiggle around the room doing the chicken dance.",
        },
        "highfive": {
            "LIV": "$N $vgive $t a highfive!",
            "": "$N $vput $p hand up for a fiver.",
        },
        "brb": {
            "STR": '$N $vhold up one finger and $vsay "be right back ($o)"',
            "": '$N $vhold up one finger and $vsay "be right back"',
        },
        "meh": {"LIV": "$N $vlook at $t and ... meh.", "": "$N ... meh."},
        "swoon": {"LIV": "$N $vlook at $t and $vswoon.", "": "$N $vswoon."},
        "telnet": {"STR": "$N $vattempt to telnet to $o."},
        "qocb": {
            "LIV": "$N $vfeel that $t should quit out and come back.",
            "": "$N $vfeel that some people should quit out and come back.",
        },
        "smack": {
            "LIV": "$N $vsmack $t.",
            "": '$N $vslap $p arm a few times, saying, "I need it bad!"',
        },
        "squeeze": {"LIV": "$N $vsqueeze $t.", "STR": "$N $vsqueeze $o."},
        "yabf": {"": "$N $vbuild yet another boot floppy."},
        "sulk": {
            "LIV": "$N $vsit in the corner and $vsulk, glaring up at $t every now and then.",
            "STR": "$N $vsulk $o.",
            "": "$N $vsulk.",
        },
        "seethe": {
            "LIV": "$N $vstare at $t, seething.",
            "": "$N $vseethe and $vfume, all the while giving everyone a baleful glare... (stand back!)",
        },
        "bonk": {"LIV": "$N $vbonk $t on the head.", "LIV STR": "$N $vbonk $t $o."},
        "comfort": {"LIV": "$N $vcomfort $t."},
        "mallet": {"LIV": "$N $vflatten $t with a giant mallet."},
        "daydream": {"LIV": "$N $vdaydream about $t."},
        "french": {
            "LIV": "$N $vpull $t in close and $vkiss $t passionately.",
            "": "$N $vpoot ohn $p vehry behste Frehnche acsente!",
        },
        "shrug": {
            "LIV": "$N $vshrug at $t.",
            "STR at LIV": "=STR LIV",
            "STR LIV": "$N $vshrug $o at $t.",
            "STR": "$N $vshrug $o.",
            "": "$N $vshrug.",
        },
        "ld": {"LIV WRD": "$N1 $v1have gone $o-dead.", "": "$N $vhave gone link-dead."},
        "bleed": {"LIV": "$N $vbleed on $t.", "": "$N $vbleed."},
        "keycaps": {"": "$N $vsay: All wiyht. Rho sritched mg kegtops awound?"},
        "hkill": {
            "": "$N $vare going to kill until no Harkonnen breathes Arakeen air."
        },
        "mmm": {
            "STR": '$N $vdrool and $vmoan, "Mmm... $o."',
            "": '$N $vrub $p tummy and $vgo, "Mmmm..."',
        },
        "weep": {"STR": "$N $vweep $o.", "": "$N $vweep."},
        "blam": {
            "LIV": '$N $vshout, "BLAM!" directly in $p1 ear.',
            "": '$N $vwave $p arms around in wild, uncontrolled gestures and $vshout, "BLAM!"',
        },
        "ooh": {"LIV": "$N $vooh and $vahh at $t.", "": "$N $vooh and $vahh."},
        "gheh": {"": '$N $vgrin, "Heh heh heh..."'},
        "tune": {"LIV": "$N $vtry to tune in Tokyo on $p1 tits."},
        "saysing": {"": '$N $vadjust $p paper hat and $vsing, "Ding! Fries are done!"'},
        "suffer": {"": "$N $vsuffer horribly."},
        "facepalm": {"": "$N $vdrop $p head into $p hand and $vsigh."},
        "dielaff": {
            "": "$N $vfall on the floor and slowly $vchoke to death laughing...."
        },
        "clap": {"LIV": "$N $vclap for $t.", "STR": "$N $vclap $o.", "": "$N $vclap."},
        "eyerape": {
            "LIV": "$N $vrape $t in $p1 eyehole.",
            "": "$N $vact like the Corinthian.",
        },
        "boogie": {"": "$N $vget $p groove on."},
        "cockslap": {
            "LIV": "$N {{$vsmash $p cock on $p1 face,,$vslap $p1 [[silly little cock++dripping pussy]]}}."
        },
        "mock": {
            "LIV": "$N $vmock $t.",
            "LIV STR": '%^BOLD%^%^BLUE%^$N $vmock $t%^RESET%^, "$o"',
            "STR": '%^BOLD%^%^BLUE%^$N $vmock%^RESET%^, "$o"',
        },
        "whimper": {
            "LIV": "$N $vwhimper at $t.",
            "STR": "$N $vwhimper $o.",
            "": "$N $vwhimper.",
        },
        "ripper": {
            "LIV": "$N $vassume $t $v1are talking about porn.",
            "": "$N $vbrag about having a good poop.",
        },
        "hiss": {"LIV": "$N $vhiss at $t.", "STR": "$N $vhiss $o.", "": "$N $vhiss."},
        "nardkick": {"LIV": "$N $vkick $t in the nards."},
        "evil": {
            "": "$N $vsprout little horns and a tail and $vturn into a cute little devil."
        },
        "muah": {"": '$N $vgo, "Muahahahahahaaaa!"'},
        "bleh": {"": '$N $vmutter, "Bleh."'},
        "jaw": {"": "$P jaw hits the floor."},
        "moan": {
            "LIV": '$N $vmoan, "$Ts".',
            "LIV STR": '$N $vmoan, "$t" $o.',
            "STR": "$N $vmoan about: $o",
            "": "$N $vmoan.",
        },
        "gighfive": {
            "LIV": "$N $vgiggle and $vhighfive $t.",
            "": "$N $vgiggle and $vhighfive nothing but air.",
        },
        "rofl": {
            "LIV": "$N $vpoint at $t and $vstart laughing hysterically.",
            "STR": '$N $vroll on the floor whimpering, "$O... oh jeezus $o..." and laughing uncontrollably.',
            "": "$N $vroll on the floor laughing.",
        },
        "ckiss": {"LIV": "$N $vkiss $t on the cheek."},
        "hold": {
            "LIV": "$N $vhold $t tightly, never wanting to let go.",
            "": "$N $vhold $p breath until $n $vare blue in the face.",
        },
        "rhinocharge": {
            "LIV": "$N $vrhino charge $t.",
            "": "$N $vget all set up for a rhino charge.",
        },
        "pace": {"STR": "$N $vpace $o.", "": "$N $vpace."},
        "nudge": {"LIV": "$N $vnudge $t knowingly.", "LIV STR": "$N $vnudge $t $o."},
        "ath": {
            "": '%^BOLD%^%^BLUE%^$N $vsing%^RESET%^, "all da hoes / \'ch yo booty on da floo ri now / (take it down to the ground)."'
        },
        "smirk": {
            "LIV": "$N $vsmirk at $t.",
            "STR": "$N $vsmirk $o.",
            "": "$N $vsmirk.",
        },
        "wormtongue": {
            "": "$N the agent of Saruman hits you. You are blind! It hits. It hits. It hits. There is a puff of smoke. Your purse feels lighter. -more-"
        },
        "scold": {"LIV": "$N $vscold $t."},
        "melt": {
            "LIV": "$N $vmelt into $p1 arms.",
            "": "$N $vmelt in a puddle of water.",
        },
        "meow": {"STR": "$N $vmeow $o.", "": "$N $vmeow."},
        "ihbt": {"": "$N $vnote that $n $vhave been trolled."},
        "eyebrowraise": {
            "LIV": "$N $vraise an eyebrow at $t.",
            "STR": "$N $vraise $o.",
            "": "$N $vraise an eyebrow.",
        },
        "bearhug": {"LIV": "$N $vgive $t a bone-crushing bearhug."},
        "eye": {
            "LIV": "$N $veye $t suspiciously.",
            "": "$N $veye everyone suspiciously.",
        },
        "wake": {
            "LIV": '$N $vgrab $t by $p1 shoulders and $vshake $to violently, screaming, "WAKE UP!"'
        },
        "roflmaobbq": {
            "": "$N $vroll on the floor laughing so hard $n $vdie and $vleak the magic BBQ sauce."
        },
        "sniff": {"LIV": "$N $vsniff $t.", "STR": "$N $vsniff $o.", "": "$N $vsniff."},
        "npoke": {"LIV": "$N $vpoke $t in the [[anus++hooter]]."},
        "shiver": {"": "$N $vshiver."},
        "grovel": {
            "LIV": "$N $vgrovel before $t.",
            "STR": "$N $vgrovel $o.",
            "": "$N $vgrovel shamelessly.",
        },
        "heh": {
            "LIV": '$N $vlook at $t and $vgo, "Heh."',
            "STR": '$N $vgo: "Heh, $o."',
            "": '$N $vgo: "Heh."',
        },
        "cry": {
            "LIV": "As tears stream down $p face, $n $vlook to $t for comfort.",
            "STR": "$N $vcry $o.",
            "": "$N $vcry.",
        },
        "unchecked": {"STR": "[ ] $o"},
        "rub": {
            "LIV": "$N $vrub $p body against $t.",
            "STR": "$N $vrub $o.",
            "": "$N $vrub $p tummy.",
        },
        "winkwink": {
            "LIV": '$N $vnudge $t and $vsay, "Nudge. Nudge. Wink. Wink. Nod\'s as good as a wink to a blind bat, eh?"',
            "": '$N $vsay, "Nudge. Nudge. Wink. Wink. Nod\'s as good as a wink to a blind bat, eh?"',
        },
        "woan": {
            "STR": '%^BOLD%^%^BLUE%^$N $vmoan and $vsay%^RESET%^, "Woah: $o"',
            "": '%^BOLD%^%^BLUE%^$N $vmoan and $vsay%^RESET%^, "Woah!"',
        },
        "frustrated": {
            "": "$N $vthrow $p hands up in the air and $vgive up in frustration."
        },
        "notme": {
            "LIV": '$N $vshake $p head at $t and $vdeclare, "Not me!"',
            "": '$N $vdeclare, "Not me!"',
        },
        "five": {
            "LIV": "$N high-$vfive $t and $vwatch $p1 hand turn bright red!",
            "": [
                'You count to five, "One, Two, Three, Four, Five..."\n',
                "$N $vare -=SUCH=- a genius. $N $vcan count to five!\n",
            ],
        },
        "cough": {
            "LIV": "$N $vcough on $p1 face.",
            "STR": '$N $vcough softly, "$o"',
            "": "$N $vcough.",
        },
        "lol": {"LIV": "$N $vlaugh out loud at $t.", "": "$N $vlaugh out loud."},
        "supz": {
            "": '$N $vput a serious mug on and $vsay, "Supz" as if it means something threatening.'
        },
        "mourn": {
            "LIV": "$N $vexpress $p grief at $p1 loss.",
            "STR": "$N $vmourn for $o.",
            "": "$N $vmourn.",
        },
        "bounce": {
            "LIV": "$N $vroll $t up into a ball and $vbounce $t around.",
            "STR": "$N $vbounce $o.",
            "": ["B O I N G !\n", "$N $vbounce around happily.\n"],
        },
        "sweep": {"LIV": "$N $vsweep the dance floor with $t."},
        "tip": {
            "LIV": "$N $vgive a stylish tip of $p hat to $t.",
            "": "$N $vgive a stylish tip of $p hat.",
        },
        "rubhands": {"": "$N $vrub $p hands together mischeviously."},
        "attack": {"LIV": "With brutal force, $n $vattack $t."},
        "rapeface": {
            "STR STR": "$N $vnote that $o rapes the face off $o.",
            "WRD STR": "$N $vnote that $o rapes the face off $o1.",
            "LIV": "$N $vrape $p1 face off.",
            "STR": "$N $vrape the face off $o.",
            "": "$N $vbegin charging up a severe and violent 10-string.",
        },
        "kiss": {
            "LIV": "$N $vkiss $t.",
            "LIV STR": "$N $vkiss $t $o.",
            "": "$N $vblow everyone a kiss.",
        },
        "toast": {
            "LIV": "$N $vtoast to $p1 health and prosperity!",
            "": '$N $vlift $p glass and $vsay, "Here, here!"',
        },
        "babelrofl": {"": "$N $vroll on the ground that laughs."},
        "smother": {"LIV": "$N $vsmother $t with passionate kisses."},
        "hate": {
            "LIV": "$N $vglare at $t with hatred.",
            "": "$N $vhate using random...",
        },
        "shandoryawn": {
            "": "$N $vchoose to ignore Shandor regarding his correctness and simply $vyawn instead."
        },
        "stomp": {
            "LIV": "$N $vstomp on $p1 head.",
            "STR": "$N $vstomp $p feet $o.",
            "": "$N $vstomp $p feet.",
        },
        "bcd": {"": "$N $vthink this is devolving into a Bleu Cheese Discussion."},
        "deepbreath": {"": "$N $vtake a deep breath."},
        "aemote": {
            "LIV": "$T <------- loser [$N]",
            "LIV STR": "$T <------- $o [$N]",
            "STR": "$N <------- $o",
        },
        "tweak": {"LIV": "$N $vtweak $p1 nipples.", "": "$N $vtweak $p nipples."},
        "breakdance": {
            "": "$N $vstagger about like a robot, moon $vwalk, $vmake a wave with $p arms, $vtwirl, $vthrow $p legs in the air like $n just $vdon't care, $vtwirl more, $vhelicopter and finally $vsettle down in a twisted pile on the floor. Wow."
        },
        "tackle": {"LIV": "$N $vtackle $t!"},
        "oh": {"": '$N $vexclaim, "Oh!"'},
        "omigod": {"": '$N $vshout, "Oh. My. God."'},
        "tkick": {
            "LIV": "$N $vkick $t in $p1 privates.",
            "LIV STR": "$N $vkick $t in $p1 $o.",
        },
        "ew": {"": '%^CYAN%^$N $vshriek%^RESET%^, "Ew! Gross!"'},
        "flick": {"LIV": "$N $vflick $p1 ear."},
        "dwowy": {
            "STR": "%^BOLD%^%^BLUE%^$N $vdeclare that the new dirty word of the week is%^RESET%^: $o"
        },
        "hmm": {
            "STR": '%^CYAN%^$N $vponder%^RESET%^, "Hmmm, $o"',
            "": '$N $vscratch $p chin and thoughtfully $vsay, "Hmmm..."',
        },
        "complain": {"STR": "$N $vcomplain $o.", "": "$N $vcomplain."},
        "nice": {
            "STR": '$N $vhave no idea what $n $vare doing, but $vthink $o is "neat," ... how nice.'
        },
        "fool": {
            "": '$N $vask, "Who\'s more foolish, the fool or the fool who follows him?"'
        },
        "jig": {
            "LIV": "$N $vlace on $p black leather shoes and $vdo a fine Irish jig around $t.",
            "OBJ": "$N $vlace on $p black leather shoes and $vdo a fine Irish jig around the $o.",
            "STR": "$N $vlace on $p black leather shoes and $vdo a fine Irish jig $o.",
            "": "$N $vlace on $p black leather shoes and $vdo a fine Irish jig.",
        },
        "eyebrow": {
            "LIV": "$N $vwiggle $p eyebrows at $t.",
            "STR": "$N $vwiggle $p eyebrows $o.\\",
            "": "$N $vwiggle $p eyebrows.",
        },
        "lag": {"": "$N $vLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG."},
        "bitchslap": {"LIV": "$N $vbitchslap $t."},
        "onward": {"": '$N $vpoint majestically, "Onward!"'},
        "slamdance": {"LIV": "$N $vslam $p chest into $t."},
        "cuss": {"LIV": "$N $vcuss at $t.", "STR": "$N $vcuss $o.", "": "$N $vcuss."},
        "yawn": {
            "LIV": "$N $vlook at $t and $vyawn.",
            "STR": "$N $vyawn $o.",
            "": "$N $vyawn.",
        },
        "dumbstruck": {
            "LIV": "$N $vstand dumbstruck, staring at $t.",
            "STR": "$N $vare dumbstruck $o.",
            "": "$N $vstand dumbstruck.",
        },
        "rubeyes": {"LIV": "$N $vrub $p1 eyes.", "": "$N $vrub $p eyes."},
        "laughjoin": {"LIV STR": "$N $vjoin $t laughing about: $o"},
        "arj": {
            "LIV": "$N $vcompress the shit out of $t.",
            "": "$N $vcompress the shit out of something.",
        },
        "nsleep": {
            "LIV": "$N $vnotice that $ts $v1need sleep badly, and $vsuggest $ts go to bed.",
            "": "$N $vneed sleep.",
        },
        "curse": {
            "LIV": "$N $vwish (by the power of $w) that $t would go straight to one of the nine hells.",
            "STR": '$N $wish (by the power of $w) that "$o" would go straight to one of the nine hells.',
            "": "$N $vtake $wp name in vain.",
        },
        "growl": {
            "LIV": "$N $vgrowl at $t.",
            "LIV STR": "$N $vgrowl at $t $o.",
            "STR": "$N $vgrowl about: $o",
            "": "$N $vgrowl.",
        },
        "rimshot": {"": "$N $vrumble out a rimshot on your pocket snare."},
        "nod": {
            "LIV": "$N $vnod at $t.",
            "LIV STR": "$N $vnod at $t $o.",
            "STR": "$N $vnod $o.",
            "": "$N $vnod.",
            "at LIV": "=LIV",
        },
        "snod": {"LIV": "$N $vsmile and $vnod at $t.", "": "$N $vsmile and $vnod."},
        "slobber": {
            "LIV": "$N $vslobber messily on $t, just like a big dog.",
            "": "$N $vslobber messily, like a big dog.",
        },
        "sob": {"STR": "$N $vsob $o.", "": "$N $vsob."},
        "hanghead": {"": "$N $vhang $p head in disappointment."},
        "ahem": {
            "": "$N $vclear $p throat and $vlook around as if someone might buy that."
        },
        "nerdslam": {
            "LIV": "$N $vgo all %^YELLOW%^Scorpion%^RESET%^, $vhook $t with ninja magic (GET OVER HERE) and $vperform a shoulder-slam-upper-cut thing. $N1 $v1are so p0wned."
        },
        "pertsovka": {
            "LIV": "$N $vhand a shot of Pertsovka to $t, accompanied by a slice of pickle.",
            "": "$N $vlook for the Pertsovka.",
        },
        "wtf": {
            "LIV": '$N $vlook at $t with a baffled expression on $p face and $vexclaim, "What the fuck?"',
            "": '%^CYAN%^$N $vexclaim%^RESET%^, "What the fuck?"',
        },
        "nag": {
            "LIV": "$N $vnag $t.",
            "": '$N $vgo, "Nag, nag, nag, nag, nag, nag, NAG!"',
        },
        "mirror": {
            "LIV": '$N $vask $t, "Is that a mirror in your pocket?"',
            "": "$N $vpreen $r in the mirror.",
        },
        "gooky": {"": "O_o"},
        "puke": {"LIV": "$N $vpuke in $p1 lap.", "": "$N $vpuke."},
        "msile": {"STR": "$N $vmsile $o.", "": "$N $vmsile."},
        "woo": {
            "LIV": "$N $vlay down some smooth pick-up lines on $t.",
            "": "$N $vpractice $p pick-up lines.",
        },
        "maddox": {
            "LIV": "$N $vinform $t that 1,372,383 fucktards don't know how these counters work.",
            "STR": '%^BOLD%^%^BLUE%^$N $vquote Maddox%^RESET%^, "$o"',
            "": "$N $vobserves new content at the Maddox site.",
        },
        "cross": {"": "$N $vcross $p fingers."},
        "flinch": {"STR": "$N $vflinch $o.", "": "$N $vflinch."},
        "blog": {"WRD STR": "$P mood: $o -- current song: $o1."},
        "stroke": {
            "LIV": "$N $vstroke $t playfully.",
            "OBJ": "$N $vstroke the $o.",
            "STR": "$N $vstroke $o.",
            "": "$N $vstroke $p hair.",
        },
        "gaze": {"": "$N $vgaze at the blue sky above."},
        "woohoo": {"": '$N $vthrow $p arms in the air and $vscream, "WOOHOO!"'},
        "iso": {"LIV": "$N $vfind $t out of conformance to the ISO standard."},
        "mae": {"": "$N $vsay: All wiyht. Rho sritched mg kegtops awound?"},
        "scratch": {"LIV": "$N $vscratch $p1 head.", "": "$N $vscratch $p head."},
        "bc": {
            "": '$N $vraise $p weapon to the sky and $vscream, "On with the body count!"'
        },
        "flash": {
            "LIV": "$N $vflash $t. $T1s $v1are impressed.",
            "LIV STR": "$N $vflash $t. $T1s $v1are $o.",
        },
        "salad": {
            "LIV": "$N $vtoss $p1 salad.",
            "": "$N $vwonder if anybody would like to toss $p salad.",
        },
        "science": {
            "LIV": "$N $vthink $p1 science is tight, yo.",
            "": "$P science is tight, yo.",
        },
        "whine": {
            "LIV": "$N $vwhine annoyingly at $t.",
            "STR": "$N $vwhine $o.",
            "": "$N $vwhine.",
        },
        "gentoo": {
            "STR": "%^BOLD%^%^GREEN%^ * %^RESET%^$o -$n %^BOLD%^%^BLUE%^[ %^GREEN%^ok%^BLUE%^ ]"
        },
        "luck": {"LIV": "$N $vwish $t good luck.", "": "$N $vare very lucky."},
        "beatings": {
            "LIV": "$N $vdecide to keep beating $t until morale improves.",
            "LIV STR": "$N $vdecide to keep beating $t until $o.",
            "": "$N $vdecide that the beatings shall continue until morale improves.",
        },
        "gogirl": {"": '$N $vsnap $p fingers and $vscream, "You go girl!"'},
        "fsmvr": {"": "$N $vtake a step to the right."},
        "ah": {"": '$N $vexclaim, "Ah."'},
        "flail": {
            "LIV": "$N $vflail $p arms about nearly striking $t!",
            "": "$N $vflail $p arms about.",
        },
        "hum": {
            "LIV": "$N $vserenade $t by humming a romantic tune.",
            "": "$N $ventertain $r by humming a tune.",
        },
        "toomanypeople": {
            "": "$N $vdecide there are too many people logged on, and $vponder a desting spree."
        },
        "jizzcuit": {
            "LIV": "$N $vmake a jizzcuit and $vhand it to $t.",
            "": "$N $vmake $r a jizzcuit.",
        },
        "shandor": {
            "LIV": "$N $vimpugn $p1 intelligence for no reason.",
            "STR": '$N $vexude knowledge about "$o."',
            "": "$N $vmake fun of Pfunk purely to further the art of it.",
        },
        "mang": {"": "$N will cut you mang."},
        "shitmouth": {
            "LIV": "$N $vshit in $p1 mouth.",
            "": "$N $vhave the worst possible bad breath.",
        },
        "peg": {
            "LIV": "$N $vpeg $t with $p mighty strap-on.",
            "STR": "$N $vfuck $o right in the ass with $p cruel strap-on.",
            "": "$N $vwear $p strap-on and $vlook for a target.",
        },
        "rage": {
            "STR": "$N $vget all emo and $vrage about $o.",
            "": "$N $vget all emo and $vrage.",
        },
        "rawr": {
            "LIV": '$N $vlook at $t and $vmeow, "Rawr!"',
            "": '$N $vmeow, "Rawr!"',
        },
        "headbang": {
            "LIV": "$N $vheadbang and $vtry to mosh on $t.",
            "STR": "$N $vbang $p head on $o.",
            "": "$N $vheadbang violently.",
        },
        "checked": {"STR": "[x] $o"},
        "dhs": {"": "$N $vhope DHS didn't hear that."},
        "gah": {
            "": '%^BOLD%^%^BLUE%^$N $vscream%^RESET%^, "GAH! Why are people doing this to me!??!"'
        },
        "snuggle": {
            "LIV": "$N $vsnuggle with $t.",
            "": [
                "$N $vlook around for someone to snuggle.",
                "$N $vlook around for someone to snuggle. C'mon, have some compassion, snuggle with $no.",
            ],
        },
        "mutter": {"STR": '$N $vmutter "$o."', "": "$N $vmutter under $p breath."},
        "cronk": {"LIV": "$N $velbow $t in the face."},
        "flex": {
            "LIV": "$N $vflex $p muscles in front of $t.",
            "STR": "$N $vflex $o.",
            "": "$N $vflex $p muscles.",
        },
        "twiddle": {
            "LIV": "$N $vtwiddle $p1 thumbs.",
            "LIV STR": "$N $vtwiddle $p1 $o.",
            "STR": "$N $vtwiddle $p $o.",
            "": "$N $vtwiddle $p thumbs.",
        },
        "huh": {
            "LIV": '$N $vlook at $t blankly and $vask, "Huh?!?"',
            "": '$N disrespectfully $vshrug and $vsay, "Huh" as if nothing could be done about it anyway.',
        },
        "shimmy": {
            "LIV": "$N shimmy shimmy $vshimmy $p1 genitals until $n1 $v1scream.",
            "": "$N shimmy shimmy $vshimmy til the break of dawn.",
        },
        "caress": {"LIV": "$N $vcaress $p1 face."},
        "doh": {"": '$N $vslap $p forehead and $vyell, "D\'OH!"'},
        "cackle": {
            "LIV": "$N $vthrow $p head back and $vcackle at $t.",
            "STR": "$N $vthrow $p head back and $vcackle $o!",
            "": "$N $vthrow $p head back and $vcackle with insane glee.",
        },
        "innocent": {"STR": '$N $vsay innocently, "$o".', "": "$N $vlook innocent."},
        "pee": {
            "LIV": "$N $vspray $t with $p yellowy fountain of justice.",
            "": "$N $vtinkle.",
        },
        "tickle": {
            "LIV": "$N $vtickle $t.",
            "LIV STR": "$N $vtickle $t $o.",
            "": "$N $vtry to tickle everyone in the room.",
        },
        "whip": {"": "$N $vcrack $p whip."},
        "propose": {"": "$N $vpropose a toast."},
        "celebrate": {"": "$N $vcelebrate."},
        "nadya": {
            "LIV": "$N $vthink Nadya is a dirty fuckin' hacker.",
            "": "Nadya smokes pole.",
        },
        "pounce": {"LIV": "$N $vpounce on $t."},
        "semishandor": {
            "": ";;;;;;;;;;;;;; for Shandor ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
        },
        "soviet": {
            "STR WRD": "In Soviet Russia, $o $o1 YOU.",
            "WRD WRD": "In Soviet Russia, $o $o1 YOU.",
        },
        "skip": {"STR": "$N $vskip $o.", "": "$N $vskip."},
        "diku": {
            "": "$N $vpoint out that even a stock merc diku can do it, so why can't Lima."
        },
        "blow": {
            "LIV": "$N $vattach to $p1 loins with style and vigor.",
            "": "$N $vblow hot air.",
        },
        "squirm": {"STR": "$N $vsquirm $o.", "": "$N $vsquirm."},
        "spit": {
            "LIV": "$N $vspit on $t.",
            "OBJ": "$N $vspit on the $o.",
            "STR": "$N $vspit $o.",
            "": "$N $vspit.",
        },
        "agree": {
            "LIV": "$N $vagree with $t.",
            "LIV STR": "$N $vagree with $t $o.",
            "STR": "$N $vagree $o.",
            "": "$N $vagree.",
        },
        "goose": {"LIV": "$N $vgoose $t."},
        "feature": {
            "LIV": "$N $vinform $t that it isn't a bug, it's a feature.",
            "": "$N $vpoint out that it isn't a bug, it's a feature.",
        },
        "burp": {
            "LIV": "$N $vburp in $p1 face.",
            "STR": "$N $vburp $o.",
            "": "$N $vburp rudely.",
        },
        "grasp": {"LIV": "$N $vgrasp $t."},
        "whew": {"": '$N $vwipe $p brow and $vexclaim, "Whew!"'},
        "spell": {"LIV": "$N $vremind $t to check $p1 spelling!!!"},
        "wine": {"": "$N $vwine like a bitch."},
        "blush": {
            "LIV": "$N $vblush furiously, glaring at $t.",
            "": [
                "You feel the heat begin to rise as your face turns a deep red.\n",
                "$N $vblush furiously.\n",
            ],
        },
        "joinlaugh": {"LIV": "$N $vlaugh along with $t about that."},
        "wiggle": {
            "LIV": "$N $vwiggle $p bottom at $t.",
            "STR": "$N $vwiggle $o.",
            "": "$N $vwiggle $p bottom.",
        },
        "banner": {
            "LIV STR": "$N $vwave a huge banner saying '$O' up $p1 face.",
            "STR": "$N $vwave a huge banner saying '$O'.",
        },
        "twirl": {"LIV": "$N $vtwirl $t in $p arms.", "": "$N $vtwirl around."},
        "pocketkiss": {
            "LIV": "$N $vsneak $p0 hands into $p1 back pockets and $vdraw $t close for a long, passionate kiss."
        },
        "zone": {
            "": "$N $vzone out and $vvisit strange lands of wonder, where magic reigns and dragons and gods roam the lands."
        },
        "forgot": {"": '$N $vexplain, "Mm... Heh heh, Oh yeah, I forgot."'},
        "snap": {"STR": "$N $vsnap $p fingers $o.", "": "$N $vsnap $p fingers."},
        "poop": {
            "LIV": "$N $vsquat and $vproduce a stinky pile of poo on $p1 chest.",
            "": "$N $vsquat and $vproduce a stinky pile of poo.",
        },
        "bkiss": {"LIV": "$N $vblow a flying kiss at $t."},
        "bigyawn": {"": "$N meant to YAWN REALLY LOUDLY."},
        "oraise": {"": "$N $vraise the other eyebrow."},
        "attention": {
            "LIV": '$N $vstomp $p foot at $t and $vscream, "Pay attention to me!"',
            "": '$N $vwhimper, "I just want attention...".',
        },
        "rape": {
            "LIV": "$N $vrape $t with a hot curling iron.",
            "STR": "$N $vviolate $o.",
            "": "$N $vwalk around threatening to rape anything that moves.",
        },
        "aww": {
            "LIV": '$N $vlook at $T sympathetically and $vsay, "Aww..."',
            "": '$N sympathetically $vsay, "Aww..."',
        },
        "thumbdown": {
            "LIV": "$N $vpoint $p thumb down at $t.",
            "": "$N $vpoint $p thumb down.",
        },
        "drool": {
            "LIV": "$N $vdrool all over $t. What a drooling geek!",
            "STR": '$N $vdrool, "$o."',
            "": "$N $vdrool, trailing tendrils of spit in $p wake.",
        },
        "fog": {"": "The fog lifts from $p0 eyes... $n $vare back."},
        "sing": {"STR": '%^BOLD%^%^BLUE%^$N $vsing%^RESET%^, "$o"', "": "$N $vsing."},
        "potter": {
            "": '%^BOLD%^%^BLUE%^$N very busily $vstate%^RESET%^, "Async potter mojo..."'
        },
        "mumble": {
            "LIV": "$N $vmumble something about $t being a dork.",
            "STR": "$N $vmumble something about $o.",
            "": "$N $vmumble.",
        },
        "goom": {
            "LIV": "$N $vlean in to whisper in $p1 ear but instead $vshout: GOOM!",
            "STR": "$N $vhate how you go to $o and then suddenly: GOOM! it's all over.",
            "": "$N $vexclaim: GOOM!",
        },
        "egrin": {"": "$N $vgrin evilly."},
        "afaik": {"": '$N $vgo, "As Far As I Know."'},
        "centmojo": {
            "": '%^BOLD%^%^BLUE%^$N very busily $vstate%^RESET%^, "A Cent Mojo Sporty!"'
        },
        "swear": {"STR": "$N $vswear $o.", "": "$N $vswear."},
        "raspberry": {"LIV": "$N $vraspberry at $t.", "": "$N $vraspberry."},
        "thwap": {
            "LIV": "$N $vthwap $t soundly making $t wince.",
            "OBJ": "$N $vthwap the $o.",
        },
        "disgust": {"LIV": "$N $vlook at $t in disgust."},
        "beg": {"LIV": "$N $vbeg $t.", "LIV STR": "$N $vbeg $t $o.", "": "$N $vbeg."},
        "makenewbie": {"LIV": 'DOH!!! $N $vdemote $t to "newbie" level.'},
        "love": {"LIV": "$N $vlove $t."},
        "book": {"STR": '%^BOLD%^%^BLUE%^$N $vquote a book%^RESET%^, "$o"'},
        "chase": {"LIV": "$N $vchase $t."},
        "dudeman": {
            "": "%^BOLD%^%^BLUE%^With veigns popping out of $p head, $n $vscream nearly incoherently%^RESET%^, \"I am not a dude. I'm not: Man. I'm a police officer. Learn to speak.\""
        },
        "ball": {
            "LIV": "$N $vnotice a ball and chain around $p1 ankle.",
            "": "$N $vremark: $500 dollars??!",
        },
        "point": {
            "LIV": "$N $vpoint at $t.",
            "OBJ": "$N $vpoint at the $o.",
            "LIV STR": '$N $vpoint at $t, "$o"',
            "STR": "$N $vpoint $o.",
            "": '$N $vpoint at $r, "Me?"',
        },
        "push": {"LIV": "$N $vgive $t a good hard push."},
        "bat": {"LIV": "$N $vbat $p eyelashes at $t.", "": "$N $vbat $p eyelashes."},
        "stare": {
            "LIV": "$N $vstare at $t.",
            "OBJ": "$N $vstare at $o.",
            "STR at LIV": "=STR LIV",
            "STR LIV": "$N $vstare $o at $t.",
            "STR": "$N $vstare $o.",
            "": "$N $vstare.",
        },
        "softheadbang": {"": "$N $vheadnod mildly aggressively."},
        "grope": {"LIV": "$N $vgrope $t.", "": "$N $vgrope blindly."},
        "horror": {
            "": '$N $vhuddle in a corner whimpering "The Horror .. the Horror."'
        },
        "kaygg": {
            "LIV": "$N $vlaugh to the left of $t.",
            "STR": "$N $vlaugh to the left about: $o",
            "": "$N $vlaugh to the left.",
        },
        "qed": {
            "": '$N $vbelieve the above is quod erat demonstrandum ("that which was to be demonstrated").'
        },
        "oggle": {
            "LIV": "$N $voggle at $p1 body.",
            "": "$N $voggle at the concept. Shapely!",
        },
        "beer": {
            "LIV": "$N $vpass a cold, frothy mug of beer to $t.",
            "": "$N $vlook around for beer.",
        },
        "chortle": {"": "$N $vchortle."},
        "excellent": {
            "": '$N $vrub $p hands together mischievously and mutters, "Excellent."'
        },
        "grunt": {
            "LIV": "$N $vgrunt at $t.",
            "STR": "$N $vgrunt $o.",
            "": "$N $vgrunt.",
        },
        "cringe": {
            "LIV": "$N $vcringe in pain at the very thought of what $ts $v1are saying.",
            "STR": "$N $vcringe $o.",
            "": "$N $vcringe.",
        },
        "fume": {"STR": "$N $vfume $o.", "": "$N $vfume."},
        "hi-pri": {"": "[!!] $N $vtry to get people to notice $no."},
        "debate": {"STR": "$N $vdebate $o.", "": "$N $vdebate."},
        "applaud": {
            "LIV": "$N $vapplaud $t.",
            "LIV STR": "$N $vapplaud $t $o.",
            "": "$N $vapplaud.",
        },
        "bojo": {
            "": "$N $vstare out the window wondering what could have happened if $n had tried."
        },
        "likesonggenerically": {
            "": "$N $vdo something a person would do when a cool song is on."
        },
        "scoff": {
            "LIV": "$N $vscoff at $t.",
            "STR": "$N $vscoff $o.",
            "": "$N $vscoff.",
        },
        "mom": {"LIV": '$N $vsay to $t, "Thanks, Mom."', "": "$N $vcry for $p mommy!!"},
        "hee": {"": '$N $vgiggle, "Hee hee!"'},
        "curtsey": {
            "LIV": "$N $vcurtsey gracefully to $t.",
            "STR": "$N $vcurtsey $o.",
            "": "$N $vcurtsey.",
        },
        "hi": {"LIV": "$N $vwave Hi! to $t.", "": "$N $vwave Hi!"},
        "pshaw": {"": '$N $vgo, "Pshaw!"'},
        "impression": {"STR": "$N $vdo $p best $o impression."},
        "kickjunk": {
            "LIV": "$N $vkick $p1 junk in.",
            "": "$N really $vwant to kick someone's junk in.",
        },
        "crikey": {
            "": '$N $vexclaim, "Crikey! That Gah-geous \'ranatang just whizzed on me boots!"'
        },
        "console": {"LIV": "$N $vconsole $t."},
        "thumbup": {
            "LIV": "$N $vpoint $p thumb up at $t.",
            "": "$N $vpoint $p thumb up.",
        },
        "pulse": {"LIV": "$N $vcheck $p1 pulse."},
        "moment": {
            "LIV": "$N $vsit quietly, observing a moment of silence in honor of $t.",
            "LIV STR": "$N $vsit quietly, observing a moment of silence in honor of $t $o.",
            "STR": "$N $vsit quietly, observing a moment of silence in honor of $o.",
            "": "$N $vsit quietly, observing a moment of silence in honor of the 891st emote.",
        },
        "blame": {"LIV": "$N $vblame $t.", "STR": "$N $vblame $o."},
        "congrat": {"LIV": "$N $vcongratulate $t."},
        "google": {
            "LIV": "$N $vthink $t should use google instead of asking next time.",
            "": "$N $vpromise to use google instead of asking next time.",
        },
        "guffaw": {
            "LIV": "$N $vlaugh boisterously at $t.",
            "STR": "$N $vguffaw $o.",
            "": "$N $vemit a loud deep burst of laughter.",
        },
        "rhide": {
            "LIV": "$N $vrun and $vhide from $t.",
            "STR": "$N $vrun and $vhide from $o.",
            "": "$N $vrun and $vhide.",
        },
        "cnorris": {"LIV": '$N $vpoint at $t and say, "Boooya."'},
        "hug": {
            "LIV": "$N $vhug $t.",
            "OBJ": "$N $vhug $o.",
            "STR": "$N $vhug $o.",
            "": "$N $vhug $r.",
        },
        "elbow": {"LIV": "$N $velbow $t."},
        "phthph": {"": "$N $vgo phthph!"},
        "eww": {"": '$N $vexclaim, "Eww!"'},
        "asap": {"": '$N $vgo, "As soon as possible."'},
        "in": {"STR": "$N immediately $vnotorize $o."},
        "sneeze": {
            "LIV": "$N $vsneeze all over $t.",
            "STR": "$N $vsneeze $o.",
            "": "$N $vsneeze.",
        },
        "gibber": {
            "LIV": "$N $vgibber incoherently at $t.",
            "": "$N $vgibber incoherently.",
        },
        "pinch": {
            "LIV": "$N $vpinch $p1 butt.",
            "": '$N $vpinch $r and $vexclaim, "Am I dreaming?!"',
        },
        "better": {"": '$N $vmutter, "That\'s Better".'},
        "montoya": {
            "LIV": '$N $vgrowl at $t and $vstate, "My name is Inigo Montoya. You killed my father. Prepare to die."',
            "": '$N $vrecite, "My name is Inigo Montoya. You killed my father. Prepare to die."',
        },
        "bad": {
            "LIV": '$N $vhit $p1 nose with a newspaper, "Bad $Tp!! Bad!!"',
            "": '$N $vstate, "That is bad."',
        },
        "glare": {
            "LIV": "$N $vglare at $t.",
            "STR": "$N $vglare $o.",
            "": "$N $vglare.",
            "at LIV": "=LIV",
        },
        "seek": {
            "LIV": "$N $vlook around for $t.",
            "": "$N $vlook around for somebody to talk to.",
        },
        "wave": {
            "WRD": "$N $vwave $o.",
            "to LIV": "$N $vwave to $t.",
            "LIV": "$N $vwave at $t.",
            "LIV STR": "$N $vwave at $t $o.",
            "": "$N $vwave.",
            "at LIV": "=LIV",
        },
        "sigh": {
            "LIV": "$N $vlook at $t and $vsigh.",
            "STR": "$N $vsigh $o.",
            "": "$N $vsigh.",
        },
        "hfive": {
            "LIV": "$N $vjump up in the air and $vgive $t a high-five!",
            "": "$N $vjump up in the air and $vswish a high-five! $N $vfall flat on $p face.",
        },
        "poke": {
            "LIV": "$N $vpoke $t in the tummy.",
            "OBJ": ".",
            "LIV STR": "$N $vpoke $t $o.",
            "STR": "$N $vpoke $o.",
            "": "It's long about noon and $n $vare pokin' at ya, pokin' at ya.",
        },
        "coffee": {
            "LIV": "$N $vpour a cup of coffee for $t.",
            "": "$N $vwander over to the coffee maker. It's time for some Joe.",
        },
        "hrofl": {"LIV": "$N $vdon't laugh at $t, $n $vlaugh with $t."},
        "ha": {"STR": '$N $vgo, "HA! $O!"', "": '$N $vlaugh, "HA!"'},
        "embrace": {"LIV": "$N $vembrace $t.", "LIV STR": "$N $vembrace $t $o."},
        "ooo": {"": '$N $vgo "ooOOooOOooOOoo"'},
        "herpes": {
            "LIV": "$N $vherpe $t. Ick!",
            "": "$N $vherpe to the left. $N $vherpe to the right. $N $vherpe all around. Damn! That science is tight.",
        },
        "pat": {
            "LIV": "$N $vpat $t on the head.",
            "LIV STR": "$N $vpat $t on the $o.",
            "": "$N $vpat $p head and $vrub $p tummy.",
        },
        "threat": {
            "LIV": '$N $vask $t, "Are you threatening me??!!"',
            "": '$N $vgo, "Are you threatening me??!!"',
        },
        "jump": {
            "LIV": "$N $vattempt to shag $n1 but $vfail as $n1 quickly $v1duck out of the way.",
            "on LIV": "$N $vjump up and down on $t.",
            "STR": "$N $vjump $o.",
            "": "$N $vjump up and down.",
        },
        "tear": {"": "A tear drops from $p eye."},
        "strut": {
            "LIV": "$N $vstrut around $t.",
            "STR": "$N $vstrut $o.",
            "": "$N $vstrut $p stuff!",
        },
        "mirmillo": {
            "": "$N $vleave while everone responds to $p latest wave of questions and stories."
        },
        "movie": {
            "LIV STR": '%^BOLD%^%^BLUE%^$N $vinform $t that the quote goes%^RESET%^, "$o"',
            "STR": '%^BOLD%^%^BLUE%^$N $vquote a movie%^RESET%^, "$o"',
            "": "$N $vcannot remember a quote from that movie.",
        },
        "coot": {
            "": '%^BOLD%^%^BLUE%^$N very busily $vstate%^RESET%^, "COOT PORN MAJESTY."'
        },
        "flesh": {"": '$N $vsay "Bah! Merely a flesh wound! I\'ve had worse!"'},
        "lmao": {
            "LIV": "$N $vare laughing $p ass off at what $t said.",
            "": "$N $vlaugh $p ass off.",
        },
        "gasp": {
            "LIV": "$N $vgasp at $t.",
            "LIV STR": "$N $vgasp at $t $o.",
            "STR": "$N $vgasp $o.",
            "": "$N $vgasp.",
        },
        "ping": {"LIV": "$N $vverify $p range to $t (one ping only)."},
        "bump": {"LIV": "$N $vbump $t.", "STR": "$N $vbump $o.", "": "$N $vbump."},
        "moon": {
            "LIV": "$N $vbend over, $vpull $p pants down, exposing $p heiny, and $vshoot $t the moon!",
            "": "$N $vbend over and $vpull $p pants down, exposing $p heiny!",
        },
        "disinme": {
            "": '%^CYAN%^$N asks%^RESET%^, "Why you disin\' me? I thought you was my ace boon coon..."'
        },
        "toodles": {
            "LIV": '$N $vwave goodby to $t and say, "Toodles!"',
            "OBJ": " begins playing with something in a magic bag, then disappears.",
        },
        "bite": {"LIV": "$N $vbite $t."},
        "cool": {
            "LIV": '$N $vlook at $t in amazement and $vshout, "Cool!"',
            "": '$N excitedly $vshout, "Cool!"',
        },
        "sad": {"": "$N $vlook sad."},
        "holdsec": {"": "$N $vsing 'Hold on a second darling...'"},
        "watch": {
            "STR": '$N $vglance at $p watch, and $vsay, "$o"',
            "": "$N $vglance at $p watch.",
        },
        "mt": {"": "$N mistold. Please disregard the previous communication."},
        "smile": {
            "LIV": "$N $vsmile at $t.",
            "STR at LIV": "$N $vsmile $o at $t.",
            "STR LIV": "$N $vsmile $o at $t.",
            "at LIV STR": "=LIV STR",
            "LIV STR": "$N $vsmile at $t $o.",
            "STR": "$N $vsmile $o.",
            "": "$N $vsmile.",
            "at LIV": "=LIV",
        },
        "fuckeye": {"LIV": "$N $vfuck $p eyes right out."},
        "bullshit": {
            "LIV": "$N $vglare at $t and $vcurse, \"That's bullshit! It's rigged!\"",
            "": "$N $vcurse, \"That's bullshit! It's rigged!\"",
        },
        "lkiss": {"LIV": "$N $vpress $p lips to $p1 in a gentle, lingering kiss."},
        "roy": {
            "": '$N $vlike to say, "%^RED%^r%^ORANGE%^o%^YELLOW%^y%^GREEN%^g%^BLUE%^bi%^MAGENTA%^v%^RESET%^."'
        },
        "omfg": {
            "LIV": '$N can\'t believe what $t just said, and $vshout out, "Oh my fucking GOD!"',
            "": '$N $vexclaim, "Oh. My. Fucking. God."',
        },
        "pant": {"STR": "$N $vpant $o.", "": "$N $vpant."},
        "confuse": {"": "$N $vlook confused."},
        "panic": {"STR": "$N $vpanic $o.", "": "$N $vpanic."},
        "shake": {
            "LIV": "$N $vshake $p head at $t.",
            "OBJ": "$N $vshake $o.",
            "STR at LIV": "=STR LIV",
            "STR LIV": "$N $vshake $p $o at $t.",
            "STR": "$N $vshake $p $o.",
            "": "$N $vshake $p head.",
        },
        "lawl": {"": "$N $vread LOL as if it were an acronym."},
        "proud": {"LIV": "$N $vare proud of $t.", "": "$N $vare proud of $r."},
        "arc": {
            "LIV": "$N $varc an eyebrow at $t.",
            "STR": "$N $varc an eyebrow $o.",
            "": "$N $varc an eyebrow.",
        },
        "guilty": {"": "$N $vlook guilty."},
        "drum": {
            "LIV": "$N $vpound out a rhythm on $p1 head. Rat-a-tat-tat.",
            "": "$N $vbang on $p drum.",
        },
        "noogie": {"LIV": "$N $vgive $t a good noogie."},
        "tweek": {
            "LIV": "$N $vtweek $p1 nipples.",
            "": "$N $vtry to find some nipples to tweek.",
        },
        "gurgle": {"STR": "$N $vgurgle $o.", "": "$N $vgurgle."},
        "wallow": {
            "LIV": "$N $vwallow over the loss of $t.",
            "STR": "$N $vwallow $o.",
            "": "$N $vwallow.",
        },
        "accuse": {
            "LIV": "$N $vaccuse $t of the crime.",
            "LIV of STR": "$N $vaccuse $t of $o.",
            "LIV STR": "$N $vaccuse $t $o.",
        },
        "gottago": {"": "$N $vsay, 'Gotta go!'"},
        "trip": {
            "LIV": "$N $vgrin evilly as $n $vtrip $t, causing $t to fall flat on $p1 face.",
            "": [
                "You trip and fall flat on your face. What a klutz! Don't you feel like a fool?!\n",
                "$N trips and falls flat on $p face. What a klutz! What a fool!\n",
            ],
        },
        "leer": {"LIV": "$N $vleer at $t."},
        "giggle": {
            "LIV": "$N $vgiggle at $t.",
            "STR": "$N $vgiggle $o.",
            "": "$N $vgiggle.",
        },
        "hiccup": {
            "WRD LIV": "$N $vhiccup $o. $T obviously caused this.",
            "LIV": "$N $vhiccup. $T obviously caused this.",
            "STR": "$N $vhiccup $o.",
            "": "$N $vhiccup.",
        },
        "nuzzle": {"LIV": "$N $vnuzzle $t warmly."},
        "fear": {
            "LIV": "$N $vfear $t.",
            "STR": "$N $vfear $o.",
            "": ["FEAR!\n", "$N lives in fear.\n"],
        },
        "disagree": {"LIV": "$N $vdisagree with $t.", "": "$N $vdisagree."},
        "threaten": {"LIV": "$N $vthreaten $t."},
        "mlp": {"STR": "$N mindlessly $vpropagate a link: <$o>."},
        "pfft": {"STR": '$N smirk, "Pfft, $o"', "": '$N $vsmirk, "Pfft."'},
        "jobud": {
            "LIV": "$N and $t jo into the vortex (no gay stuff).",
            "STR": "$N $vwish to jo on $o (no gay stuff).",
            "": "$N $vwish to jo into the vortex (no gay stuff).",
        },
        "bodyslam": {
            "LIV": "$N $vbodyslam $t into the wall.",
            "LIV STR": "$N $vbodyslam $t $o.",
        },
        "war": {"": "$N $vcry havoc and $vlet loose the dogs of war."},
        "eyeroll": {"LIV": "$N $vroll $p eyes at $t.", "": "$N $vroll $p eyes."},
        "writhe": {
            "LIV": "$N $vwrithe all over $t.",
            "OBJ": "$N $vwrithe all over $o.",
            "STR": "$N $vwrithe $o.",
            "": "$N $vwrithe in agony!",
        },
        "roflmao": {"": "$N $vroll on the floor laughing $p ass off."},
        "cower": {
            "LIV": "$N $vcower before $t.",
            "STR": "$N $vcower $o.",
            "": "$N $vcower in fear.",
        },
        "boggle": {
            "LIV": "$N $vboggle at $t.",
            "OBJ": "$N $vboggle at $o.",
            "STR": "$N $vboggle $o.",
            "": "$N $vboggle.",
        },
        "rip": {"": '%^CYAN%^$N $vsay%^RESET%^, "Yes, quite, rippin\' good laugh."'},
        "hmmph": {"": '$N $vlower $p gaze and $vgrumble, "Hmmph."'},
        "omg": {
            "LIV": '$N $vdrop $p jaw, $vlook at $t and $vsay, "Oh. My. God!"',
            "": '$N $vexclaim, "Oh. My. God."',
        },
        "yarf": {"": "$N $vbuild yet another root floppy."},
        "purr": {
            "LIV": "$N $vcrawl up onto $p1 lap and $vpurr like a cat.",
            "STR": "$N $vpurr $o.",
            "": "$N $vpurr.",
        },
        "hump": {
            "LIV": "$N lasciviously $vgrind $r on $p1 leg.",
            "LIV WRD": "$N $vgrind $r on $p1 $o.",
            "STR LIV": "$N $o $vgrind $r on $p1 leg.",
            "STR": '$N slowly $vstrip off $p armor. After $n seductively $vremove $p underthings, $n $vare rapturous in $p beauty. As $n $vrub $r to climax, undulating wildly, $n $vmoan, "$o! Oh god! $o!"',
            "": "$N dry $vhump the ground.",
        },
        "fcomm": {"": '$N $vsay, "What we have here is a failure to communicate."'},
        "yhbt": {"LIV": "$N $vpoint out that $t $v1have been trolled."},
        "ratiocinative": {"": "$N $vuse $p ratiocinative powers."},
        "pontificate": {"STR": '%^BOLD%^BLUE%^$N $vpontificate%^RESET%^, "$o."'},
        "sue": {
            "LIV": "$N $vsue $t for being a fucktard.",
            "LIV STR": "$N $vsue $t for being $o.",
        },
        "spanktushy": {"LIV": "$N $vspank $t on $p1 cute little tushy."},
        "uhoh": {"": '$N $vcover $p mouth and $vmumble, "Uh oh."'},
        "themanagerrant": {
            "": "%^CYAN%^The Manager says%^RESET%^, \"$M, I hear that XP crashes at 5% cpu utilization. I need you to write a program that scans every server for processor utilization. If any processes exceeds the 5% high water mark, we need to reboot the server immediately and perform a full system audit to track down the errant process. When the audit is complete, we'll need to schedule a conference call with the CEO, the vendor of the application, our Microsoft support manager, the system owner and the system admin. Following the con-call, please write up an audit summary, a full report on the process in question and begin to plan how we can schedule these processes to run so that they never run concurrently. Can you have this process completed this afternoon? Thanks."
        },
        "grumble": {
            "LIV": "$N $vgrumble at $t.",
            "LIV STR": "$N $vgrumble at $t about $o.",
            "STR": "$N $vgrumble $o.",
            "": "$N $vgrumble.",
        },
        "wtg": {
            "LIV": '$N $vgive $t a highfive and $vshout, "Way to go!"',
            "": '$N $vshout, "Way to go!"',
        },
        "duck": {"": "$N $vduck."},
        "masai": {
            "LIV": "$N $vjump around like the Masai and even $vgive $t a hair-flick. ",
            "": "$N $vstart jumping around like the Masai.",
        },
        "thank": {
            "LIV": "$N $vthank $t.",
            "OBJ": "$N $vthank $o.",
            "LIV STR": "$N $vthank $t $o.",
            "STR": "$N $vthank $o.",
            "": "$N $vthank $w for $p luck.",
        },
        "smeil": {
            "LIV": "$N $vsmeil at $t.",
            "STR at LIV": "$N $vsmeil $o at $t.",
            "STR LIV": "$N $vsmeil $o at $t.",
            "at LIV STR": "=LIV STR",
            "LIV STR": "$N $vsmeil at $t $o.",
            "STR": "$N $vsmeil $o.",
            "": "$N $vsmeil.",
            "at LIV": "=LIV",
        },
        "wow": {"": '$N excitedly $vdeclare, "Wow!"'},
        "grandeur": {"": "$N $vbegin to get delusions of Grandeur."},
        "happy": {"": "$N $vare happy."},
    },
    "adverbs": [
        "absently",
        "absentmindedly",
        "accidentally",
        "adamantly",
        "adeptly",
        "adorably",
        "agreeably",
        "aggravatedly",
        "aggressively",
        "aimlessly",
        "amazedly",
        "amusedly",
        "angelically",
        "angrily",
        "annoyingly",
        "annoyedly",
        "anxiously",
        "appreciatively",
        "arousedly",
        "astonishedly",
        "audibly",
        "automatically",
        "autonomically",
        "awfully",
        "awkwardly",
        "badly",
        "bashfully",
        "beautifully",
        "belligerently",
        "bemusedly",
        "benignly",
        "bitterly",
        "blandly",
        "bluntly",
        "boldly",
        "boredly",
        "bravely",
        "briefly",
        "brightly",
        "briskly",
        "broadly",
        "brotherly",
        "brutally",
        "busily",
        "calmly",
        "carefully",
        "carelessly",
        "cautiously",
        "charmingly",
        "cheerfully",
        "childishly",
        "clumsily",
        "coldly",
        "comprehensively",
        "confidently",
        "confirmingly",
        "confusedly",
        "contemptuously",
        "contentedly",
        "convincingly",
        "coolly",
        "courageously",
        "cowardly",
        "crazily",
        "creatively",
        "criminally",
        "critically",
        "cunningly",
        "curiously",
        "cutely",
        "cynically",
        "dangerously",
        "darkly",
        "deadly",
        "decliningly",
        "deeply",
        "defiantly",
        "definitely",
        "degradingly",
        "demonically",
        "depressively",
        "desperately",
        "devilishly",
        "devotedly",
        "dirtily",
        "disappointedly",
        "disgustedly",
        "disgustingly",
        "disrespectfully",
        "doubtfully",
        "doubtlessly",
        "dreadfully",
        "dreamily",
        "drily",
        "drunkenly",
        "dumbly",
        "eagerly",
        "educationally",
        "egocentrically",
        "egoistically",
        "embarrassedly",
        "emphatically",
        "endearingly",
        "endlessly",
        "enduringly",
        "energetically",
        "enormously",
        "enthusiastically",
        "enviously",
        "erotically",
        "evilly",
        "excellently",
        "exhaustedly",
        "expectantly",
        "facinatedly",
        "faintly",
        "faithfully",
        "fanatically",
        "fatherly",
        "fervently",
        "fiendishly",
        "fiercefully",
        "firmly",
        "fitfully",
        "flatly",
        "flirtingly",
        "fondly",
        "foolishly",
        "frankly",
        "frantically",
        "frenetically",
        "frequently",
        "friendly",
        "fundamentally",
        "funnily",
        "furiously",
        "generously",
        "gently",
        "ghastly",
        "gleefully",
        "gloomily",
        "goofily",
        "gracefully",
        "grandfatherly",
        "grandmotherly",
        "gravely",
        "greedily",
        "grimly",
        "groowily",
        "guidingly",
        "handsomely",
        "happily",
        "hard",
        "harmonically",
        "hastedly",
        "heartbrokenly",
        "heavenly",
        "heavily",
        "hellishly",
        "helpfully",
        "helplessly",
        "heroically",
        "hesitantly",
        "honestly",
        "hopefully",
        "hopelessly",
        "hornily",
        "horribly",
        "hotly",
        "humbly",
        "humourlessly",
        "hungrily",
        "hurriedly",
        "hysterically",
        "idiotically",
        "idly",
        "ignorantly",
        "immediately",
        "impatiently",
        "impishly",
        "impotently",
        "inanely",
        "innocently",
        "insanely",
        "instantly",
        "intelligently",
        "intendly",
        "interestedly",
        "introspectively",
        "intuitively",
        "invincibly",
        "invisibly",
        "invulnerably",
        "inwardly",
        "ironically",
        "irresistably",
        "jealously",
        "jeeringly",
        "jokingly",
        "jovially",
        "joyfully",
        "knowingly",
        "kindly",
        "laconically",
        "lazily",
        "levelly",
        "lewdly",
        "lightly",
        "loftily",
        "loosely",
        "lonely",
        "longingly",
        "loudly",
        "lovingly",
        "lustfully",
        "madly",
        "manfully",
        "maniacally",
        "masochistically",
        "meaningfully",
        "melancholically",
        "mercifully",
        "mercilessly",
        "merrily",
        "mildly",
        "mischievously",
        "misguidingly",
        "mockingly",
        "moodily",
        "motherly",
        "mournfully",
        "musically",
        "mysteriously",
        "nastily",
        "naturally",
        "naughtily",
        "nervously",
        "nicely",
        "nobly",
        "noisily",
        "noticeably",
        "notoriously",
        "oddly",
        "officially",
        "officiously",
        "omniously",
        "omnipotently",
        "openly",
        "painfully",
        "passionately",
        "patiently",
        "patronizingly",
        "peacefully",
        "perfectly",
        "personally",
        "physically",
        "playfully",
        "pleasantly",
        "pointedly",
        "politely",
        "poorly",
        "potently",
        "powerfully",
        "powerlessly",
        "professionally",
        "profoundly",
        "protectively",
        "proudly",
        "puzzledly",
        "questioningly",
        "quickly",
        "quietly",
        "quizzically",
        "radiantly",
        "randomly",
        "rampantly",
        "rapidly",
        "rebelliously",
        "recklessly",
        "recursively",
        "regretfully",
        "reluctantly",
        "remotely",
        "reproachfully",
        "respectfully",
        "reverently",
        "rigoriously",
        "royally",
        "rudely",
        "sadistically",
        "sadly",
        "sagely",
        "sarcastically",
        "satanically",
        "savagely",
        "sceptically",
        "scornfully",
        "searchingly",
        "secretly",
        "seductively",
        "sensually",
        "seriously",
        "sexily",
        "shamefully",
        "shamelessly",
        "shapelessly",
        "sharply",
        "sheepishly",
        "shrewdly",
        "shrilly",
        "shyly",
        "sickly",
        "silently",
        "simultaneously",
        "skillfully",
        "sleepily",
        "slightly",
        "slowly",
        "slyly",
        "smartly",
        "smilingly",
        "smoothly",
        "sneakily",
        "sniffingly",
        "softly",
        "solemnly",
        "sort of",
        "sothingly",
        "sourly",
        "spontaneously",
        "sternly",
        "strangely",
        "strictly",
        "stubbornly",
        "stupidly",
        "suddenly",
        "sufferingly",
        "suggestively",
        "surprisingly",
        "sweetly",
        "swiftly",
        "tearfully",
        "teasingly",
        "temporarely",
        "tenderly",
        "terribly",
        "thankfully",
        "theoretically",
        "thoughtfully",
        "tightly",
        "tiredly",
        "tragically",
        "triumphantly",
        "trustfully",
        "unbearably",
        "understandably",
        "understandingly",
        "undeterminedly",
        "uneasily",
        "unexpectedly",
        "unhappily",
        "unknowingly",
        "unlikely",
        "unpolitely",
        "unwillingly",
        "urgently",
        "utterly",
        "vaguely",
        "viciously",
        "vigorously",
        "violently",
        "virtually",
        "voluptuously",
        "vulnerably",
        "warmly",
        "weakly",
        "wearily",
        "whimsically",
        "wholeheartedly",
        "wibbly",
        "wickedly",
        "wildly",
        "willingly",
        "wimpily",
        "wisely",
        "wishfully",
        "wistfully",
        "wobbly",
        "wonderingly",
        "wonderfully",
        "yellowishly",
        "zanily",
        "approvingly",
        "uncontrollably",
        "affectionately",
        "suavely",
        "stoically",
    ],
}
